In [2]:
from preprocess import preprocess_data

In [3]:
df = preprocess_data(r"E:\IMT\2nd Sem\Project\Implementation\Data\NF-UQ-NIDS-v2.csv")

📥 Loading data...

ParserError: Error tokenizing data. C error: out of memory

In [ ]:
df

,src_port,dst_port,protocol,duration,packets_count,fwd_packets_count,bwd_packets_count,total_payload_bytes,fwd_total_payload_bytes,bwd_total_payload_bytes,...,dst_ip_octet_1,dst_ip_octet_2,dst_ip_octet_3,dst_ip_octet_4,year,month,day,hour,minute,second
0,0.754949,0.006593,0.0,0.000021,0.000649,0.000863,0.000578,0.000278,0.000239,0.000264,...,0.320755,0.082353,0.317647,0.784314,0.0,1.0,0.037037,0.000000,0.779661,0.949153
1,0.755499,0.006593,0.0,0.000003,0.000352,0.000628,0.000248,0.000052,0.000541,0.000018,...,0.235849,0.952941,0.894118,0.188235,0.0,1.0,0.037037,0.000000,0.796610,0.016949
2,0.755270,0.001053,0.0,0.000413,0.000108,0.000235,0.000083,0.000000,0.000000,0.000000,...,0.792453,0.850980,0.027451,0.556863,0.0,1.0,0.037037,0.000000,0.779661,0.966102
3,0.755774,0.006593,0.0,0.000007,0.000568,0.000863,0.000454,0.000210,0.000258,0.000194,...,0.698113,0.764706,0.054902,0.439216,0.0,1.0,0.037037,0.000000,0.796610,0.050847
4,0.755728,0.006593,0.0,0.000008,0.000568,0.000863,0.000454,0.000210,0.000258,0.000194,...,0.698113,0.764706,0.054902,0.439216,0.0,1.0,0.037037,0.000000,0.796610,0.050847
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45560,0.960191,0.006624,0.0,0.000048,0.000270,0.000471,0.000206,0.000022,0.000209,0.000010,...,0.792453,0.121569,0.250980,0.435294,0.0,0.0,0.518519,0.222222,0.610169,0.016949
45561,0.764184,0.006593,0.0,0.000000,0.000000,0.000078,0.000000,0.000000,0.000000,0.000000,...,0.235849,0.647059,0.192157,0.494118,0.0,0.0,0.518519,0.222222,0.610169,0.559322
45562,0.006426,0.763396,0.0,0.000000,0.000000,0.000000,0.000041,0.000000,0.000000,0.000000,...,0.792453,0.121569,0.250980,0.435294,0.0,0.0,0.518519,0.222222,0.610169,0.576271
45563,0.488712,0.035285,0.0,0.000000,0.000000,0.000078,0.000000,0.000000,0.000000,0.000000,...,0.792453,0.121569,0.250980,0.435294,0.0,0.0,0.518519,0.222222,0.627119,0.169492
45564,0.762871,0.006593,0.0,0.000000,0.000000,0.000078,0.000000,0.000000,0.000000,0.000000,...,0.089623,0.141176,0.125490,0.333333,0.0,0.0,0.518519,0.222222,0.627119,0.372881

In [ ]:
df.describe()

,src_port,dst_port,protocol,duration,packets_count,fwd_packets_count,bwd_packets_count,total_payload_bytes,fwd_total_payload_bytes,bwd_total_payload_bytes,...,dst_ip_octet_1,dst_ip_octet_2,dst_ip_octet_3,dst_ip_octet_4,year,month,day,hour,minute,second
count,45565.000000,45565.000000,45565.0,4.556500e+04,45565.000000,45565.000000,45565.000000,45565.000000,45565.000000,45565.000000,...,45565.000000,45565.000000,45565.000000,45565.000000,45565.0,45565.000000,45565.000000,45565.000000,45565.000000,45565.000000
mean,0.612665,0.130136,0.0,2.438537e-03,0.000337,0.000540,0.000272,0.000157,0.000609,0.000119,...,0.598261,0.349028,0.414898,0.234297,0.0,0.142785,0.499940,0.343031,0.461398,0.482898
std,0.277859,0.265916,0.0,1.565198e-02,0.005732,0.004935,0.006545,0.006550,0.007481,0.006528,...,0.317979,0.343852,0.234262,0.240999,0.0,0.349857,0.213442,0.188966,0.301038,0.262126
min,0.000000,0.000000,0.0,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.598507,0.001053,0.0,2.877989e-10,0.000027,0.000078,0.000041,0.000000,0.000000,0.000000,...,0.146226,0.121569,0.270588,0.098039,0.0,0.000000,0.518519,0.222222,0.203390,0.288136
50%,0.685360,0.001053,0.0,2.085067e-06,0.000216,0.000392,0.000165,0.000018,0.000150,0.000004,...,0.792453,0.121569,0.270588,0.098039,0.0,0.000000,0.555556,0.333333,0.491525,0.474576
75%,0.793171,0.123148,0.0,3.673767e-04,0.000243,0.000392,0.000165,0.000037,0.000430,0.000026,...,0.792453,0.858824,0.662745,0.435294,0.0,0.000000,0.555556,0.555556,0.762712,0.677966
max,1.000000,1.000000,0.0,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
df.fillna(0, inplace=True)
df.info()
df.isna().sum().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45565 entries, 0 to 45564
Columns: 333 entries, src_port to second
dtypes: float16(2), float64(330), int64(1)
memory usage: 115.2 MB

np.int64(0)